### PR TITLE
Remove warnings due to lacking variables

### PR DESCRIPTION
**Pull request by MinchinWeb**
OpenSCAD was throwing warnings, I think as a result of having a wall pattern at the same time as using the efficient floor options.

image

This seems to fix it, by defining the missing variables `efficient_floor` and `floor_thickness`. Now the warnings are gone!

### CODE REVIEW

**Comment by MinchinWeb** [comment]
Oops, it got closed by accident.

**Comment by ostat** [comment]
I broke a bunch of stuff with some recent 'optimisations'. I have fixed some of them but have a few to still do.
I will review and pull these in once I am done. 
Thanks for submitting :)

**Comment by ostat** [comment]
This has been fixed already. Sorry about that. If you can check the latest and see if anything was missed?

**Comment by MinchinWeb** [comment]
Yeah, it seems to be fixed on my side! I'll re-open if something comes up.

**Pull request closed without merging**
