### PR TITLE
Add full support for fractional increments and improve socket selection

### PR DESCRIPTION
**Pull request by Monniasza**
Hi. I've added support for fractional increments of basic cups, item holders, and trays. I've also added drop-down menu for socket holders.

### CODE REVIEW

**Comment by ostat** [comment]
thanks

**Comment by jprisant** [comment]
I am confused by this update. Ever since the following, the file has been broken for me. 

The Item holder is so wonderfully flexible... I have found a lot of uses for keeping the label. 
```openscad
label = "disabled"; // ["disabled", "left", "right", "center", "leftchamber", "rightchamber", "centerchamber"]
// Width of the label in number of units, or zero means full width
label_width = 0;  // .01
```

**Comment by jprisant** [comment]
Here is a quick example of something I created with one of the earlier versions of **gridfinity_item_holder.scad** that uses the depth. label, and separators.

image

**Comment by ostat** [comment]
> Here is a quick example of something I created with one of the earlier versions of **gridfinity_item_holder.scad** that uses the depth. label, and separators.
> 
> image

I will fix that, would you mi

> I am confused by this update. Ever since the following updated to **gridfinity_item_holder.scad**, the file has been broken for me.
> 
> The Item holder is so wonderfully flexible... I have found a lot of uses for keeping the label.
> 
> ```scad
> label = "disabled"; // ["disabled", "left", "right", "center", "leftchamber", "rightchamber", "centerchamber"]
> // Width of the label in number of units, or zero means full width
> label_width = 0;  // .01
> ```

I can fix that. Would you mind raising an issue so i dont forget?

**Comment by jprisant** [comment]
Wahoo! This repo is the absolute best!!

**Comment by jprisant** [comment]
✅Done

https://github.com/ostat/gridfinity_extended_openscad/issues/22

**Pull request merged**
