### PR TITLE
bugfix for spacers

### PR DESCRIPTION
**Pull request by danielsan80**
There was a wrong offset of che negative parts

image
image

### CODE REVIEW

**Comment by ostat** [comment]
relates to bug #77

**Comment by ostat** [comment]
@danielsan80, thanks for raising this issue and for the PR. 
While this does appear to fix the issue, I believe the actual mistake was an undeclared variable. Once I removed that the position was corrected.

I created  #77, and have pushed a fix for the change. Can you take a look and confirm it now works.

**Comment by danielsan80** [comment]
> I created #77, and have pushed a fix for the change. Can you take a look and confirm it now works.

In `main` it doesn't work yet, I'm sorry.
image

I have just set `spacer` = true in `gridfinity_basic_cup.scad`

**Comment by ostat** [comment]
I forgot to push the change. Sorry about that. Could you try again :)

**Comment by danielsan80** [comment]
ok. It works!

**Comment by ostat** [comment]
Closing as is fixed now

**Pull request closed without merging**
